/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as PortefeuilleRouteImport } from './routes/portefeuille'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPortfolioRouteImport } from './routes/api/portfolio'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiTinkInitRouteImport } from './routes/api/tink/init'
import { Route as ApiTinkConnectUrlRouteImport } from './routes/api/tink/connect-url'
import { Route as ApiTinkCallbackRouteImport } from './routes/api/tink/callback'
import { Route as ApiPortfolioTickersRouteImport } from './routes/api/portfolio.tickers'
import { Route as ApiPortfolioIdRouteImport } from './routes/api/portfolio.$id'
import { Route as ApiAlertsIdReadRouteImport } from './routes/api/alerts.$id.read'

const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefeuilleRoute = PortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioRoute = ApiPortfolioRouteImport.update({
  id: '/api/portfolio',
  path: '/api/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinkInitRoute = ApiTinkInitRouteImport.update({
  id: '/api/tink/init',
  path: '/api/tink/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinkConnectUrlRoute = ApiTinkConnectUrlRouteImport.update({
  id: '/api/tink/connect-url',
  path: '/api/tink/connect-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinkCallbackRoute = ApiTinkCallbackRouteImport.update({
  id: '/api/tink/callback',
  path: '/api/tink/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioTickersRoute = ApiPortfolioTickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => ApiPortfolioRoute,
} as any)
const ApiPortfolioIdRoute = ApiPortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPortfolioRoute,
} as any)
const ApiAlertsIdReadRoute = ApiAlertsIdReadRouteImport.update({
  id: '/$id/read',
  path: '/$id/read',
  getParentRoute: () => ApiAlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboard': typeof DashboardRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/reglages': typeof ReglagesRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/portfolio': typeof ApiPortfolioRouteWithChildren
  '/api/portfolio/$id': typeof ApiPortfolioIdRoute
  '/api/portfolio/tickers': typeof ApiPortfolioTickersRoute
  '/api/tink/callback': typeof ApiTinkCallbackRoute
  '/api/tink/connect-url': typeof ApiTinkConnectUrlRoute
  '/api/tink/init': typeof ApiTinkInitRoute
  '/api/alerts/$id/read': typeof ApiAlertsIdReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboard': typeof DashboardRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/reglages': typeof ReglagesRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/portfolio': typeof ApiPortfolioRouteWithChildren
  '/api/portfolio/$id': typeof ApiPortfolioIdRoute
  '/api/portfolio/tickers': typeof ApiPortfolioTickersRoute
  '/api/tink/callback': typeof ApiTinkCallbackRoute
  '/api/tink/connect-url': typeof ApiTinkConnectUrlRoute
  '/api/tink/init': typeof ApiTinkInitRoute
  '/api/alerts/$id/read': typeof ApiAlertsIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboard': typeof DashboardRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/reglages': typeof ReglagesRoute
  '/api/alerts': typeof ApiAlertsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/portfolio': typeof ApiPortfolioRouteWithChildren
  '/api/portfolio/$id': typeof ApiPortfolioIdRoute
  '/api/portfolio/tickers': typeof ApiPortfolioTickersRoute
  '/api/tink/callback': typeof ApiTinkCallbackRoute
  '/api/tink/connect-url': typeof ApiTinkConnectUrlRoute
  '/api/tink/init': typeof ApiTinkInitRoute
  '/api/alerts/$id/read': typeof ApiAlertsIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/dashboard'
    | '/portefeuille'
    | '/reglages'
    | '/api/alerts'
    | '/api/dashboard'
    | '/api/portfolio'
    | '/api/portfolio/$id'
    | '/api/portfolio/tickers'
    | '/api/tink/callback'
    | '/api/tink/connect-url'
    | '/api/tink/init'
    | '/api/alerts/$id/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/dashboard'
    | '/portefeuille'
    | '/reglages'
    | '/api/alerts'
    | '/api/dashboard'
    | '/api/portfolio'
    | '/api/portfolio/$id'
    | '/api/portfolio/tickers'
    | '/api/tink/callback'
    | '/api/tink/connect-url'
    | '/api/tink/init'
    | '/api/alerts/$id/read'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/dashboard'
    | '/portefeuille'
    | '/reglages'
    | '/api/alerts'
    | '/api/dashboard'
    | '/api/portfolio'
    | '/api/portfolio/$id'
    | '/api/portfolio/tickers'
    | '/api/tink/callback'
    | '/api/tink/connect-url'
    | '/api/tink/init'
    | '/api/alerts/$id/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  DashboardRoute: typeof DashboardRoute
  PortefeuilleRoute: typeof PortefeuilleRoute
  ReglagesRoute: typeof ReglagesRoute
  ApiAlertsRoute: typeof ApiAlertsRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiPortfolioRoute: typeof ApiPortfolioRouteWithChildren
  ApiTinkCallbackRoute: typeof ApiTinkCallbackRoute
  ApiTinkConnectUrlRoute: typeof ApiTinkConnectUrlRoute
  ApiTinkInitRoute: typeof ApiTinkInitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefeuille': {
      id: '/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof PortefeuilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio': {
      id: '/api/portfolio'
      path: '/api/portfolio'
      fullPath: '/api/portfolio'
      preLoaderRoute: typeof ApiPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tink/init': {
      id: '/api/tink/init'
      path: '/api/tink/init'
      fullPath: '/api/tink/init'
      preLoaderRoute: typeof ApiTinkInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tink/connect-url': {
      id: '/api/tink/connect-url'
      path: '/api/tink/connect-url'
      fullPath: '/api/tink/connect-url'
      preLoaderRoute: typeof ApiTinkConnectUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tink/callback': {
      id: '/api/tink/callback'
      path: '/api/tink/callback'
      fullPath: '/api/tink/callback'
      preLoaderRoute: typeof ApiTinkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/tickers': {
      id: '/api/portfolio/tickers'
      path: '/tickers'
      fullPath: '/api/portfolio/tickers'
      preLoaderRoute: typeof ApiPortfolioTickersRouteImport
      parentRoute: typeof ApiPortfolioRoute
    }
    '/api/portfolio/$id': {
      id: '/api/portfolio/$id'
      path: '/$id'
      fullPath: '/api/portfolio/$id'
      preLoaderRoute: typeof ApiPortfolioIdRouteImport
      parentRoute: typeof ApiPortfolioRoute
    }
    '/api/alerts/$id/read': {
      id: '/api/alerts/$id/read'
      path: '/$id/read'
      fullPath: '/api/alerts/$id/read'
      preLoaderRoute: typeof ApiAlertsIdReadRouteImport
      parentRoute: typeof ApiAlertsRoute
    }
  }
}

interface ApiAlertsRouteChildren {
  ApiAlertsIdReadRoute: typeof ApiAlertsIdReadRoute
}

const ApiAlertsRouteChildren: ApiAlertsRouteChildren = {
  ApiAlertsIdReadRoute: ApiAlertsIdReadRoute,
}

const ApiAlertsRouteWithChildren = ApiAlertsRoute._addFileChildren(
  ApiAlertsRouteChildren,
)

interface ApiPortfolioRouteChildren {
  ApiPortfolioIdRoute: typeof ApiPortfolioIdRoute
  ApiPortfolioTickersRoute: typeof ApiPortfolioTickersRoute
}

const ApiPortfolioRouteChildren: ApiPortfolioRouteChildren = {
  ApiPortfolioIdRoute: ApiPortfolioIdRoute,
  ApiPortfolioTickersRoute: ApiPortfolioTickersRoute,
}

const ApiPortfolioRouteWithChildren = ApiPortfolioRoute._addFileChildren(
  ApiPortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  DashboardRoute: DashboardRoute,
  PortefeuilleRoute: PortefeuilleRoute,
  ReglagesRoute: ReglagesRoute,
  ApiAlertsRoute: ApiAlertsRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiPortfolioRoute: ApiPortfolioRouteWithChildren,
  ApiTinkCallbackRoute: ApiTinkCallbackRoute,
  ApiTinkConnectUrlRoute: ApiTinkConnectUrlRoute,
  ApiTinkInitRoute: ApiTinkInitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
