/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as PortefeuilleRouteImport } from './routes/portefeuille'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTinkInitRouteImport } from './routes/api/tink/init'
import { Route as ApiTinkCallbackRouteImport } from './routes/api/tink/callback'

const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefeuilleRoute = PortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinkInitRoute = ApiTinkInitRouteImport.update({
  id: '/api/tink/init',
  path: '/api/tink/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTinkCallbackRoute = ApiTinkCallbackRouteImport.update({
  id: '/api/tink/callback',
  path: '/api/tink/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboard': typeof DashboardRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/reglages': typeof ReglagesRoute
  '/api/tink/callback': typeof ApiTinkCallbackRoute
  '/api/tink/init': typeof ApiTinkInitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboard': typeof DashboardRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/reglages': typeof ReglagesRoute
  '/api/tink/callback': typeof ApiTinkCallbackRoute
  '/api/tink/init': typeof ApiTinkInitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboard': typeof DashboardRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/reglages': typeof ReglagesRoute
  '/api/tink/callback': typeof ApiTinkCallbackRoute
  '/api/tink/init': typeof ApiTinkInitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/dashboard'
    | '/portefeuille'
    | '/reglages'
    | '/api/tink/callback'
    | '/api/tink/init'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/dashboard'
    | '/portefeuille'
    | '/reglages'
    | '/api/tink/callback'
    | '/api/tink/init'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/dashboard'
    | '/portefeuille'
    | '/reglages'
    | '/api/tink/callback'
    | '/api/tink/init'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  DashboardRoute: typeof DashboardRoute
  PortefeuilleRoute: typeof PortefeuilleRoute
  ReglagesRoute: typeof ReglagesRoute
  ApiTinkCallbackRoute: typeof ApiTinkCallbackRoute
  ApiTinkInitRoute: typeof ApiTinkInitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefeuille': {
      id: '/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof PortefeuilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tink/init': {
      id: '/api/tink/init'
      path: '/api/tink/init'
      fullPath: '/api/tink/init'
      preLoaderRoute: typeof ApiTinkInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tink/callback': {
      id: '/api/tink/callback'
      path: '/api/tink/callback'
      fullPath: '/api/tink/callback'
      preLoaderRoute: typeof ApiTinkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  DashboardRoute: DashboardRoute,
  PortefeuilleRoute: PortefeuilleRoute,
  ReglagesRoute: ReglagesRoute,
  ApiTinkCallbackRoute: ApiTinkCallbackRoute,
  ApiTinkInitRoute: ApiTinkInitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
